// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnxNo8LXZhjEsxXbqwbgicrL5M0kMsYhg',
    appId: '1:920143385125:web:cef18168292db069a6a5cc',
    messagingSenderId: '920143385125',
    projectId: 'floracare-b38a5',
    authDomain: 'floracare-b38a5.firebaseapp.com',
    storageBucket: 'floracare-b38a5.firebasestorage.app',
    measurementId: 'G-QHHPVR26C8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk0dz-zWCbR3Fx3ixWwv9xolPdWXkWCwo',
    appId: '1:920143385125:android:e625c81281f9331fa6a5cc',
    messagingSenderId: '920143385125',
    projectId: 'floracare-b38a5',
    storageBucket: 'floracare-b38a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2OnGDKwzqRyaZ6QxUpyEdvGB1_R46XIw',
    appId: '1:920143385125:ios:205df621c49a7ebaa6a5cc',
    messagingSenderId: '920143385125',
    projectId: 'floracare-b38a5',
    storageBucket: 'floracare-b38a5.firebasestorage.app',
    iosBundleId: 'com.example.floraCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2OnGDKwzqRyaZ6QxUpyEdvGB1_R46XIw',
    appId: '1:920143385125:ios:205df621c49a7ebaa6a5cc',
    messagingSenderId: '920143385125',
    projectId: 'floracare-b38a5',
    storageBucket: 'floracare-b38a5.firebasestorage.app',
    iosBundleId: 'com.example.floraCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnxNo8LXZhjEsxXbqwbgicrL5M0kMsYhg',
    appId: '1:920143385125:web:eb142ee31d178077a6a5cc',
    messagingSenderId: '920143385125',
    projectId: 'floracare-b38a5',
    authDomain: 'floracare-b38a5.firebaseapp.com',
    storageBucket: 'floracare-b38a5.firebasestorage.app',
    measurementId: 'G-07YT0Y9EHR',
  );
}
